#!/usr/bin/env bash

set -x

APPID=$1
VERSION=$2
BUILD=$3
LAYER=$4
WORKDIR=$APPID

SEARCH_REF=$(grep "$REF" "$LL_PICA_FLATPAK_REFS_FILE")

if [[ -z $SEARCH_REF ]];
then
    "${LL_PICA_FLATPAK_PATH}/ll-pica-flatpak-utils" generate_ref_cache
fi

ostree --repo="$FLATHUB_CACHE" pull "$REF"
rm -rf "$WORKDIR" && mkdir -p "$WORKDIR"
ostree --repo="$FLATHUB_CACHE" checkout "$REF" "$WORKDIR/flatpak"

FLATPAK_COMMAND=$(grep '^command=' $WORKDIR/flatpak/metadata | awk -F'=' '{print $2}')
FLATPAK_RUNTIME=$(grep '^runtime=' "$WORKDIR"/flatpak/metadata | awk -F'=' '{print $2}' | awk -F'/' '{print $1}')
FLATPAK_RUNTIME_VERSION=$(grep '^runtime=' "$WORKDIR"/flatpak/metadata | awk -F'=' '{print $2}' | awk -F'/' '{print $3}')

LINGLONG_BASE_NAME="org.deepin.base.flatpak.$(echo "$FLATPAK_RUNTIME"|awk -F'.' '{print $2}')"
LINGLONG_BASE_VERSION="$(echo "${FLATPAK_RUNTIME_VERSION/.0/.}.0.0.0" | awk -F'[-.]' 'BEGIN {OFS="."} {print $1,$2,$3}')"

if [[ -n $BASE ]];
then
    LINGLONG_BASE_NAME=$BASE
fi

if [[ -n $BASE_VERSION ]];
then
    LINGLONG_BASE_VERSION=$BASE_VERSION
fi

tee "$WORKDIR"/linglong.yaml <<EOF
version: "1"
package:
  id: $APPID
  name: $APPID
  version: $VERSION
  kind: app
  description: flatpak runtime environment on linglong

command: [$FLATPAK_COMMAND]
base: $LINGLONG_BASE_NAME/$LINGLONG_BASE_VERSION

build: |
  cp -rf flatpak/files/* \$PREFIX
EOF

if $BUILD;
then
    cd "$WORKDIR"
    ll-builder build

    if $LAYER;
    then
        ll-builder export --layer
    else
        ll-builder export
    fi
fi